### ISSUE TITLE
分割大文件时拖动UI卡顿问题

### ISSUE THREAD

**Issue by ichieh42** [aoguai/SplitFiles#6]
**描述错误(对错误的清晰而简明的描述)：**

虽然现在已经采用其他线程处理IO任务，但是在拖拽UI界面时依然能感觉到界面闪烁

初步判断是连续发送事件信号`self.trigger.emit(...)`导致的QT渲染变慢

---

**复现步骤(重现行为的步骤)：**

选定一个大小在9G的csv文件，点击“分割文件”后观察，此时拖拽UI界面正常

在正式进入分割方法既进度条走动后，此时拖拽界面出现界面卡顿闪烁现象

---

**预期行为(对您期望发生的事情的清晰而简明的描述)：**

---

**截图(如果可以，请添加截图以帮助解释您的问题)：**

---

**系统信息(请填写以下信息)：**
   - 操作系统：Windows
   - 版本：Windows 11 专业版 23H2

---

**附加上下文(在此处添加有关问题的任何其他上下文)：**
我想讨论下如何优化现有逻辑

**Comment by aoguai** [comment]
其实我技术也有限，对异步和多线程不是很了解。
但是我总觉得现在的 `SplitFiles.py` 和 `GUI.py` 还能继续解耦。

最好的情况就是 `SplitFiles.py` 只负责按行分割文件不对 GUI 做操作，也就是其中最好不涉及QT部分。

或者这种闪烁可能就是 QT 自身不可避免的问题。

**Comment by ichieh42** [comment]
我这里有两种实现方法：
1. 每次切割开始进度信号发送只有100次，在`SplitFiles.py`里控制发送次数。
2. 在界面UI文件`GUI.py`里控制渲染次数，计算相对于总行数`total_lines`的比例。

效率比较如下
|  实现方法1   | 实现方法2  |
|  ----  | ----  |
| trigger.emit(1, ...)调用100次  | trigger.emit(1, ...)调用N次 |
| progress_bar.setValue()调用100次  | progress_bar.setValue()调用100次 |

是否第一种情况比较好？

**Comment by aoguai** [comment]
或许可以新创建`ProgressBarUI`的python类，将所有的进度条的布局以及槽函数放到该类中。

`SplitFiles.py` 应该归回更纯粹的负责按行分割文件功能类的作用。

因为以后还打算支持多文本文件同时处理，你这样写只会增加代码耦合度。

**Comment by ichieh42** [comment]
你是对的，我花费一些时间分析一下`ProgressBarUI`需要做些什么

**Comment by ichieh42** [comment]
https://github.com/aoguai/SplitFiles/pull/7

因为后期可能增加文件大小来切割文件，我觉得ProgressBarUI只需要接收百分比即可
而切割进度的百分比应该由子线程SplitFiles计算返回

我还没有计算过，但粗略观察后可以注意到：减少了进程间信息交换和QT频繁地渲染之后，用户体验会有一个明显的提升
