### ISSUE TITLE
字符解码错误

### ISSUE THREAD

**Issue by ichieh42** [aoguai/SplitFiles#9]
**描述错误(对错误的清晰而简明的描述)：**

用最新版切割文件时由于解码错误程序直接闪退

---

**复现步骤(重现行为的步骤)：**

正常切割一个csv文件，csv文件由navicat生成

---

**预期行为(对您期望发生的事情的清晰而简明的描述)：**

---

**截图(如果可以，请添加截图以帮助解释您的问题)：**
```
Traceback (most recent call last):
  File "D:\Source\SplitFiles\src\SplitFiles.py", line 45, in run
    self.split_file_by_size()
  File "D:\Source\SplitFiles\src\SplitFiles.py", line 106, in split_file_by_size
    self.total_lines = sum(1 for _ in f)
                       ^^^^^^^^^^^^^^^^^
  File "D:\Source\SplitFiles\src\SplitFiles.py", line 106, in <genexpr>
    self.total_lines = sum(1 for _ in f)
                          ^^^^^^^^^^^^^^
  File "D:\Software\miniconda3\Lib\encodings\ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd4 in position 2637: ordinal not in range(128)
```
---

**系统信息(请填写以下信息)：**
   - 操作系统：Windows
   - 版本：Windows 11 专业版 23H2

---

**附加上下文(在此处添加有关问题的任何其他上下文)：**

**Comment by ichieh42** [comment]
当指定编码为utf-8之后是正常的
``` python
    with open(file_path, 'rb') as file:
        # 读取文件前 1024 字节，用于判断文件编码
        return 'utf-8'
        # return chardet.detect(file.read(1024))['encoding']
```
只读取前1024个字符时返回字符编码为ascii；但是其实后面的内容是使用utf8编码的
这导致了使用ascii解码对应的内容时报错

所以应该怎么修改呢？

**Comment by aoguai** [comment]
> 当指定编码为utf-8之后是正常的
> 
> ```python
>     with open(file_path, 'rb') as file:
>         # 读取文件前 1024 字节，用于判断文件编码
>         return 'utf-8'
>         # return chardet.detect(file.read(1024))['encoding']
> ```
> 
> 只读取前1024个字符时返回字符编码为ascii；但是其实后面的内容是使用utf8编码的 这导致了使用ascii解码对应的内容时报错
> 
> 所以应该怎么修改呢？

适当延长字节长度试试？感觉是库的问题，但是我这边也没有找到同时可以兼容UTF-8\ASCII\GBK的很好的解决办法。

**Comment by ichieh42** [comment]
切割大文件时没办法确认多少个字节就能准确判断出编码吧？
如果盲目加大字节大小的话又损耗了性能
我觉得可以加一个下拉框给用户自己选择，默认值是UTF-8

**Comment by aoguai** [comment]
> 切割大文件时没办法确认多少个字节就能准确判断出编码吧？ 如果盲目加大字节大小的话又损耗了性能 我觉得可以加一个下拉框给用户自己选择，默认值是UTF-8

可行

**Comment by aoguai** [comment]
- #8
